dist: trusty
language: java
jdk:
- openjdk8

addons:
 sonarcloud:
  organization: "ludovicodiiorio"
  token:
   secure: "a576c308ce208b21c9650ff98ffb203d7482b288"

script:
- ant build
- sonar-scanner
